### ISSUE TITLE
Drag-and-drop of .groovy files doesn't open Script Editor

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-legacy#149]
Dragging a `.groovy` file onto the Fiji toolbar will open a normal `TextWindow` instead of the script editor.

See the related [discussion on the forum](http://forum.imagej.net/t/error-drag-and-drop-with-groovy-scripts/4217/7?u=imagejan).

**Comment by ctrueden** [comment]
Ha, I figured out why: [check out this regex](https://github.com/imagej/imagej-legacy/blob/imagej-legacy-0.23.5/src/main/java/net/imagej/legacy/DefaultLegacyHooks.java#L297).

**Comment by tferr** [comment]
I just came across this also. I had not noticed it before because the other [supported extensions](http://mrhaki.blogspot.ca/2011/10/groovy-goodness-default-groovy-script.html) (`.gvy .gy .gsh`) work fine. I'm guessing changing the regex to `".*\\.[0-9A-Za-z]{1,6}"` would immediately work.
Is that a good fix? Or is there a reason to support only 3 char extensions?

**Comment by ctrueden** [comment]
I am wondering why we want to limit it at all. Why not just: `.*\\.[0-9A-Za-z]+`?

**Comment by tferr** [comment]
Perfect. The less restrictions the better, IMO (I just thought there had been some deliberate reason for the limitation).

**Comment by ctrueden** [comment]
I infer that the deliberate reason was to treat files like `my.dot.delineated.file.with.a.super.long.filename` according to the expectations of the user. Or maybe there was even a concrete case where someone had a file with a `.` in it, but the text after the dot was not a file extension. Still, the 4-character limit is a hack, and I'd rather just remove it. File paths like that are highly uncommon, IMHO.
