### ISSUE TITLE
ImageJ2 LUTs not respected in legacy UI

### ISSUE THREAD

**Issue by rejsmont** [imagej/imagej-legacy#164]
Hi,

I have been fiddling around with LUTs / ColorTables in IJ2 API and noticed that if you set them using this API, but are working with legacy (now still default) UI, the LUT settings are ignored.

```
imageDisplay = ds.createDisplay(image)
imageDisplay.getActiveView().setColorTable(colorTable, 0)
```

In Legacy mode, the LUT setting is ignored. In IJ2 mode, the LUT is correctly set. 

Funny enough, ``setColorTable`` does not work unless ``DatasetView`` is registered with ``ImageDisplay``, otherwise I am getting a ``NullPointerException``:

```
imageView = ids.createDataView(image)
imageView.setColorTable(colorTable, 0)

java.lang.NullPointerException
	at net.imagej.display.DefaultDatasetView.setColorTable(DefaultDatasetView.java:195)
```

**Comment by rejsmont** [comment]
On a note, ``DatasetView.setComposite(boolean composite)`` works as expected in both Legacy and IJ2 UI.

**Comment by ctrueden** [comment]
Thanks @rejsmont. There are honestly a lot of problems like this with using the ImageJ Common APIs and having them not reflected in the ImageJ1 UI. And I'm sorry to say it is unlikely these issues will be tackled this year, even though I wish the ImageJ Legacy integration was more complete and seamless. Part of the reason is that we still need to iterate more on the ImageJ Common design itself, so it feels rather like "shifting sands" to build the full legacy support on top of it before the IJ2 API has stabilized.

**Comment by rejsmont** [comment]
Oh well. I will try to pinpoint where it could come from. Maybe I would be able to come up with a pull request :)

**Comment by rejsmont** [comment]
Closed (won't fix):

As far as I understand, the legacy API relies on ``ImagePlus`` representation of IJ2's ``ImageDisplay``. As LUTs from ImagePlus are directly represented in the ImgPlus class (wrapped in a dataset) it pulls LUTs from that source and is unable to merge LUT information from ``DatasetView``.

Please see the above comment for a correct way of setting LUTs using IJ2 API for display in the legacy interface.

**Comment by rejsmont** [comment]
For those how got stuck on this - see this forum thread: http://forum.imagej.net/t/imagej2-misbehaves-with-xyzc-images/5782
