### ISSUE TITLE
Support array inputs for IJ1 macros

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-legacy#167]
The IJ1 macro language supports arrays as a variable type in `ij.macro.Variable`. We should consider changing `net.imagej.legacy.plugin.IJ1MacroEngine` to support arrays as input from script parameters, e.g. `File[]` returning a list of file paths, just as the `getFileList()` macro function does, and `int[]` and `String[]` returning macro arrays as well (as soon as there are corresponding input widgets available, of course).

**Comment by ctrueden** [comment]
@imagejan I pushed a commit which might do the trick. But not tested yet.

Here is a small macro that _should_ test the situation:
```javascript
#@ int integer
#@ String string
#@ File file
#@ String[] (required = false, persist = false, value = {"a", "b"}) strings

print("integer = " + integer);
print("string = " + string);
print("file = " + file);
print("strings = " + strings); //substring(strings, 4, 6));
```

The print statement should _fail_ when the `strings` variable is actually an array, since ImageJ 1.x does not allow you to print arrays directly.

**Comment by ctrueden** [comment]
Closed by fc7fdc0acfc851c8cf08bb985a90db46c73225e2.

**Comment by Jindil** [comment]
I managed to use the 
`#@ File[] file` 
however I don't manage to have the 
`#@ String[] (required = false, persist = false, value = {"a", "b"}) strings` 
rendered in the resulting GUI window.

**Comment by ctrueden** [comment]
@Jindil That's right—you cannot harvest `String[]` with the Swing widget dialog yet.

This issue is about injecting the default value of the parameter, which in the example above is `{"a", "b"}` i.e. an array of length 2, with the first element being `"a"` and the second being `"b"`. The following variation makes this more obvious:
```javascript
#@ int integer
#@ String string
#@ File file
#@ String[] (required = false, persist = false, value = {"a", "b"}) strings

print("integer = " + integer);
print("string = " + string);
print("file = " + file);
print("string0 = " + strings[0]);
print("string1 = " + strings[1]);
print("string2 = " + strings[2]);
```

You'll notice that `string0` and `string1` print `a` and `b` respectively, while the print statement about `string2` yields an error message.
