### ISSUE TITLE
Script editor autocompletion for "exit"

### ISSUE THREAD

**Issue by miura** [imagej/imagej-legacy#218]
Autocompletion in the scritpt editor for the function "exit" has a small bug. See the image below. 

![image](https://user-images.githubusercontent.com/272781/57450851-ea4ec080-725f-11e9-84ce-881511ba9079.png)

**Comment by ctrueden** [comment]
Looking at the `functions.html`, it appears that this `exit` function is the only one that has multiple invocations separated by an ` or ` outside the parentheses.

@haesleinhuepf Our priority should be to make sure that `functions.html` works as written automatically without tweaking, right? So that we can easily keep it updated as time goes on by dropping in new versions? If so, we need to write some special-case parsing for this odd case, right?

**Comment by rasband** [comment]
I updated the file at
   http://wsr.imagej.net/developer/macro/functions.html

so that exit and exit("error message") are separate entries.

```
<a name=exit></a>
<b>exit</b><br>
Terminates execution of the macro. 
<p>

<b>exit("error message")</b><br>
Terminates execution of the macro and displays an error message. 
<p>

```

**Comment by ctrueden** [comment]
@haesleinhuepf I tried to update the locally bundled `functions.html` resource to finish addressing this issue, but it seems there are many differences between the local copy and the one on the remote site. So I wasn’t sure what the process is for updating it? Did you make modifications manually? If so, do you have automation to remake them when things change? And can we commit that script to the repo? Or if not: would it make sense to create such a script?
