### ISSUE TITLE
 ROI manage

### ISSUE THREAD

**Issue by lanhexiang** [imagej/imagej-legacy#304]
![QQ截图20240527115033](https://github.com/imagej/imagej-legacy/assets/170908865/eb59b0b9-845e-4f45-9cf1-29ce0c0fb366)
I can not open ROI manage，it say ‘’Overlay required‘’  what should I do？

**Comment by miura** [comment]
Hi @lanhexiang 
Did you try [Analyze > Tools > ROI Manager...] ? 
Kota

**Comment by miura** [comment]
@lanhexiang  
Great that it works. 
Please note that "Issues" in the ImageJ GitHub repository is intended more for issues related to software development. For questions about ImageJ usage, it's much better to post your questions within the image.sc forum [https://forum.image.sc/](https://forum.image.sc/). This is a strong recommendation because there will be more responses. 

Cheers, 
Kota

**Comment by lanhexiang** [comment]
yes, you are right , I just found that thank you for reminding me

**Comment by lanhexiang** [comment]
it's my first time to communicate with foreigner. it's a wonderful feeling. Could you give some advise ? where else could there be such a conversation.

**Comment by miura** [comment]
Hi @lanhexiang 

If it's something related to image processing and analysis, just go ahead and ask your questions there in the forum. There will be kind responses from all over the world. 

For now, I close this issue as I believe it is done. 

Cheers, 
Kota
