### ISSUE TITLE
Create a non-consuming log handler

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-legacy#54]
Depends on https://github.com/scijava/scijava-common/issues/84

Currently there are cases where we are not logging events properly in ImageJ 1.x. For example, if we use the `ThreadService` to spawn a new thread and it throws an exception, it is highly likely that the exception will be caught by the `DefaultEventService` and logged.

We would really like to give the legacy UI a chance to respond to these errors, without competing with other service implementations.

Once we are able to implement non-consuming `Handler` plugins, we can create a new `LegacyLogHandler` that passes messages to `IJ.log` and exceptions to `IJ.handleException`. This can then co-exist with other handler implementations.

**Comment by hinerm** [comment]
Possible overlap with #97 ?

**Comment by ctrueden** [comment]
We opted for a different approach; see #97. It would be too disruptive to ImageJ1 workflows to start populating the log with any new information, since unfortunately, people rely on the Log behaving _exactly_ the same as it did before, forever (see e.g. [Fiji bug 984](http://fiji.sc/bugzilla/show_bug.cgi?id=984) where we tried to change this).
